config/routes.rb
Rails.application.routes.draw do
  root to: 'microposts#index'

  devise_for :kitchencars, controllers: {
    sessions: 'kitchencars/sessions',
    registrations: 'kitchencars/registrations',
  }

  resources :kitchencars, only: [:show, :index] do
    resources :menus, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  resources :microposts, only: [:index, :create, :edit, :show, :update, :destroy]
  resources :maps, only: [:index]
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :kitchencar
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true
  validates :price, presence: true
  has_one_attached :image
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @menu = Menu.new
  end

  def create
    @menu = current_kitchencar.menus.build(menu_params)
    if @menu.save
      flash[:success] = "メニューを作成しました"
      redirect_to kitchencar_menus_path
    else
      render 'menus/new'
    end
  end

  def index
    @menus = Menu.with_attached_image.where(kitchencar_id: params[:kitchencar_id])
  end

  def edit
  end

  def update
    if @menu.update(menu_params)
      flash[:success] = "更新しました!"
      redirect_to kitchencar_menus_path
    else
      render 'menus/edit'
    end
  end

  def destroy
    @menu.destroy
    flash[:success] = "削除しました!"
    redirect_to request.referrer || kitchencar_menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:name, :description, :price, :image)
  end

  def correct_user
    @menu = current_kitchencar.menus.find_by(id: params[:id])
    redirect_to root_url if @menu.nil?
  end

end

app/views/menus/edit.html.erb
<%= form_with model: @menu, url: kitchencar_menu_path, method: :patch, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field mb-4 w-75 center-block">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control'%>
    <% if @menu.errors.any? %>
      <% errors_hash(@menu, :name).each do |error_msg| %>
        <p class="text-xs text-danger"><%= error_msg %></p>
      <% end %>
    <% end %>
  </div>

   <div class="field mb-4 w-75 center-block">
    <%= f.label :description %>
    <%= f.text_area :description, autofocus: true, class: 'form-control' %>
  </div>

  <div class="field mb-4 w-75 center-block">
    <%= f.label :price %>
    <%= f.text_field :price, autofocus: true, class: 'form-control' %>
    <% if @menu.errors.any? %>
      <% errors_hash(@menu, :price).each do |error_msg| %>
        <p class="text-xs text-danger"><%= error_msg %></p>
      <% end %>
    <% end %>
  </div>

  <div class="image mb-4 w-75 center-block">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions text-center mb-4">
    <%= f.submit "更新", class: 'btn btn-primary w-25'%>
  </div>
<% end %>

app/views/menus/index.html.erb
<div class="mb-4">
  <% if current_kitchencar && params[:kitchencar_id] == current_kitchencar.id.to_s %>
    <%= link_to "メニュー作成", new_kitchencar_menu_path %>
  <% else %>
    <%= link_to '戻る', kitchencar_path(params[:kitchencar_id]) %>
  <% end %>
</div>
<div class="row row-cols-2 row-cols-md-3 g-4 mb-4">
  <% @menus.each do |menu| %>
    <div class="col">
      <div class="card h-100">
        <% if menu.image.attached? %>
          <%= image_tag menu.image.variant(resize: '1200x1000!').processed, class: 'card-img-top' %>
        <% else %>
          <%= image_tag "no_image.jpg", class: 'card-img-top' %>
        <% end %>
        <div class="card-body">
          <div class="card-title" style="font-size: 22px;">
            <%= menu.name %>
          </div>
          <p class="card-text" style="font-size: 20px">
            <%= menu.price %>円
          </p>
          <p class="card-text" style="font-size: 18px;">
            <%= menu.description %>
          </p>
          <% if current_kitchencar && params[:kitchencar_id] == current_kitchencar.id.to_s %>
            <%= link_to edit_kitchencar_menu_path(current_kitchencar, menu) do%>
              <i class="far fa-edit fa-lg text-dark"></i>
            <% end %>
            <%= link_to kitchencar_menu_path(current_kitchencar, menu), method: :delete, data: { confirm: "削除しますか？" } do %>
              <i class="far fa-trash-alt fa-lg text-dark"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/menus/new.html.erb
<%= form_with model: @menu, url: kitchencar_menus_path, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field mb-4 w-75 center-block">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control'%>
    <% if @menu.errors.any? %>
      <% errors_hash(@menu, :name).each do |error_msg| %>
        <p class="text-xs text-danger"><%= error_msg %></p>
      <% end %>
    <% end %>
  </div>

  <div class="field mb-4 w-75 center-block">
    <%= f.label :description %>
    <%= f.text_area :description, autofocus: true, class: 'form-control' %>
  </div>

  <div class="field mb-4 w-75 center-block">
    <%= f.label :price %>
    <%= f.text_field :price, autofocus: true, class: 'form-control' %>
    <% if @menu.errors.any? %>
      <% errors_hash(@menu, :price).each do |error_msg| %>
        <p class="text-xs text-danger"><%= error_msg %></p>
      <% end %>
    <% end %>
  </div>

  <div class="image mb-4 w-75 center-block">
    <%= f.label :image %><br />
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions text-center mb-4">
    <%= f.submit "作成", class: 'btn btn-primary w-25'%>
  </div>
<% end %>