config/routes.rb
Rails.application.routes.draw do
  root to: 'microposts#index'

  devise_for :kitchencars, controllers: {
    sessions: 'kitchencars/sessions',
    registrations: 'kitchencars/registrations',
  }

  resources :kitchencars, only: [:show, :index] do
    resources :menus, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  resources :microposts, only: [:index, :create, :edit, :show, :update, :destroy]
  resources :maps, only: [:index]
end

app/models/kitchencar.rb
class Kitchencar < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many_attached :portraits
  has_many :microposts, dependent: :destroy
  has_many :menus, dependent: :destroy
  validates :name, presence: true
  validates :location, presence: true
end

app/controllers/kitchencars/confirmations_controller.rb
# frozen_string_literal: true

class Kitchencars::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/kitchencars/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Kitchencars::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/kitchencars/passwords_controller.rb
# frozen_string_literal: true

class Kitchencars::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/kitchencars/registrations_controller.rb
# frozen_string_literal: true

class Kitchencars::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    super
    @kitchencar.portraits.purge
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :location, :introduction, portraits: []])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :location, :introduction, portraits: []])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    kitchencar_path(current_kitchencar)
  end
end

app/controllers/kitchencars/sessions_controller.rb
# frozen_string_literal: true

class Kitchencars::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/kitchencars/unlocks_controller.rb
# frozen_string_literal: true

class Kitchencars::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/kitchencars_controller.rb
class KitchencarsController < ApplicationController
  before_action :exist_kitchencar, only: [:show]

  def show
    @microposts = @kitchencar.microposts.with_attached_images.page(params[:page]).per(9)
    @menus = Menu.with_attached_image.where(kitchencar_id: params[:id])[0..2]
  end

  def index
    redirect_to root_url
  end

  private

  def exist_kitchencar
    @kitchencar = Kitchencar.find_by(id: params[:id])
    if @kitchencar.nil?
      redirect_to root_url
    end
  end
end

app/views/kitchencars/show.html.erb
<div class="container">
  <div class="mb-4 text-right">
    <%= link_to "プロフィールを編集", edit_kitchencar_registration_path if current_kitchencar && params[:id] == current_kitchencar.id.to_s %>
  </div>

  <div class="mb-3">
    <span class=" border border-info rounded p-2 text-info ">
        <%= @kitchencar.location %>
    </span>
  </div>

  <div id="Header" class="border-bottom border-secondary mb-4">
    <font size="7" face="Osaka">
      <%= @kitchencar.name %>
    </font>
  </div>

  <div id="carouselExampleIndicators" class="carousel slide mb-5" data-mdb-ride="carousel">
    <div class="carousel-inner">
      <% if @kitchencar.portraits.attached? %>
        <% @kitchencar.portraits.each_with_index do |portrait, i| %>
          <% if i == 0 %>
            <div class="carousel-item active">
              <%= image_tag portrait.variant(resize: "500x300!").processed, class: 'd-block w-100 img-responsive' %>
            </div>
          <% else %>
            <div class="carousel-item">
              <%= image_tag portrait.variant(resize: "500x300!").processed, class: 'd-block w-100 img-responsive' %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-mdb-target="#carouselExampleIndicators"
      data-mdb-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-mdb-target="#carouselExampleIndicators"
      data-mdb-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <h3 class="mb-6"><%= @kitchencar.introduction %></h3>

  <h3>メニュー (<%= @kitchencar.menus.count %>)</h3>
  <div class="row row-cols-2 row-cols-md-3 g-4 mb-4">
    <% @menus.each do |menu| %>
      <div class="col">
        <div class="card h-100">
          <% if menu.image.attached? %>
            <%= image_tag menu.image.variant(resize: '1200x1000!').processed, class: 'card-img-top' %>
          <% else %>
            <%= image_tag "no_image.jpg", class: 'card-img-top' %>
          <% end %>
          <div class="card-body">
            <div class="card-title" style="font-size: 22px;">
              <%= menu.name %>
            </div>
            <p class="card-text" style="font-size: 20px">
              <%= menu.price %>円
            </p>
            <p class="card-text" style="font-size: 18px;">
              <%= menu.description %>
            </p>
            <% if current_kitchencar && params[:kitchencar_id] == current_kitchencar.id.to_s %>
              <%= link_to edit_kitchencar_menu_path(current_kitchencar, menu) do %>
                <i class="far fa-edit fa-lg text-dark"></i>
              <% end %>
              <%= link_to kitchencar_menu_path(current_kitchencar, menu), method: :delete, data: { confirm: "削除しますか？" } do %>
                <i class="far fa-trash-alt fa-lg text-dark"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="mb-4 text-right" style="font-size: 18px;">
    <%= link_to 'すべてのメニューはこちら >>', kitchencar_menus_path(@kitchencar) %>
  </div>

  <% if @kitchencar.microposts.any? %>
    <h3>投稿 (<%= @kitchencar.microposts.count %>)</h3>
    <div class="row row-cols-2 row-cols-md-3 g-4 mb-4">
      <% @microposts.each do |micropost| %>
        <div class="col">
          <div class="card h-100">
            <%= link_to micropost_path(micropost) do %>
              <% if micropost.images.attached? %>
                <%= image_tag micropost.images[0].variant(resize: '1200x1000!').processed, class: 'card-img-top' %>
              <% else %>
                <%= image_tag "no_image.jpg", class: 'card-img-top' %>
              <% end %>
            <% end %>
            <div class="card-body">
              <p class="card-text" style="font-size: 18px;">
                <%= micropost.content %>
              </p>
              <div class="card-footer bg-transparent">
                <%= time_ago_in_words(micropost.created_at) %>前
                <span class="mx-3">
                <% if micropost.kitchencar == current_kitchencar %>
                  <%= link_to edit_micropost_path(micropost), class: 'text-dark' do %>
                    <i class="far fa-edit fa-lg"></i>
                  <% end %>
                    <%= link_to micropost_path(micropost), method: :delete, class: 'text-dark', data: { confirm: "削除しますか？" } do %>
                    <i class="far fa-trash-alt fa-lg"></i>
                  <% end %>
                <% end %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="text-center">
  <%= paginate @microposts %>
</div>