config/routes.rb
Rails.application.routes.draw do
  root to: 'microposts#index'

  devise_for :kitchencars, controllers: {
    sessions: 'kitchencars/sessions',
    registrations: 'kitchencars/registrations',
  }

  resources :kitchencars, only: [:show, :index] do
    resources :menus, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  resources :microposts, only: [:index, :create, :edit, :show, :update, :destroy]
  resources :maps, only: [:index]
end

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright: KitchenTracker
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'KitchenTracker', root_path, class: 'navbar-brand' %>
    <button type="button" class="navbar-toggler justify-content-end" data-bs-toggle="collapse" data-bs-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="fas fa-bars"></span>
    </button>

    <div class="collapse navbar-collapse" id="Navber">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item active">
          <%= link_to 'ホーム', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'MAP', maps_path, class: "nav-link" %>
        </li>
        <% if current_kitchencar %>
          <li class="nav-item">
            <%= link_to "プロフィール", kitchencar_path(current_kitchencar), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_kitchencar_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "お店の方はこちら", new_kitchencar_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KitchenTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css" rel="stylesheet"/>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%#= debug(params) if Rails.env.development? %>
  </body>
  <!-- MDB -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"></script>
  <!-- bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>